### ISSUE TITLE
Why is version 2.3 not compatible to magento 2.2.* ?

### ISSUE THREAD

**Issue by BrocksiNet** [mygento/configsync#8]
Hey guys, 

I see that there is a requirement on "magento/module-deploy": "100.3.*" in composer.json but I do not see that there is something used in the code that will not work with magento 2.2? Do I missed something or you just want to put new features and bugfixes on the new version?

Greetings bjoern

**Comment by luckyraul** [comment]
use ~2.2.0 tags

**Comment by BrocksiNet** [comment]
I know I can do this but I just want to know what you are using that is NOT compatible ... I do not see something special that will not work in both versions.

**Comment by luckyraul** [comment]
We do not want to make a common version. We maintain both versions separately.

**Comment by BrocksiNet** [comment]
Okay. Thx for this info.
